version: '3'
services:
    php-apache:
        image: php:7.2-apache
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
            - ./server/httpd.conf:/etc/apache2/apache2.conf
            - ./server/php.ini:/usr/local/etc/php/php.ini
