version: '3'
services:
    php-apache:
        build:
            context: .
            dockerfile: apache.Dockerfile
        environment:
            SSL_CERT_LOCATION: '/etc/ssl/private/ssl.cert'
            SSL_KEY_LOCATION: '/etc/ssl/private/ssl.key'
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
            - ./server/httpd.conf:/etc/apache2/apache2.conf
            - ./server/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./server/php.ini:/usr/local/etc/php/php.ini
            - ./server/ssl.crt:/etc/ssl/private/ssl.cert
            - ./server/ssl.key:/etc/ssl/private/ssl.key
        depends_on:
            - database
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_pw_shh
            MYSQL_DATABASE: webshop
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - "9906:3306"
        volumes:
            - ./database:/docker-entrypoint-initdb.d
